import { expect, test } from "@playwright/test"

test("runs from minimum IP to reviewed and restores after refresh", async ({ page }) => {
  await page.goto("/")
  await page.getByLabel("称呼").fill("示例团长")
  await page.getByLabel("真实经历").fill("三年社区团购运营经历，服务过多个社区")
  await page.getByLabel("擅长领域").fill("社区团购运营")
  await page.getByLabel("目标人群").fill("希望拓展本地业务的人")
  await page.getByLabel("表达特点").fill("直接、实在、有案例")
  await page.getByLabel("不能说的内容").fill("不承诺确定收益")
  await page.getByRole("button", { name: "完成初始化并生成选题" }).click()
  await expect(page.getByText("今天，先确定真正值得拍的一条")).toBeVisible()
  await expect(page.getByRole("button", { name: "当前 IP 示例团长" })).toBeVisible()
  await page.getByRole("button", { name: "选择这个方向" }).first().click()
  await expect(page.getByRole("button", { name: "生成 3 篇文案" })).toHaveCount(0)
  await expect(page.getByText("选择今天的口播稿")).toBeVisible()
  await page.getByRole("button", { name: "选择这版并进入质检" }).click()
  await expect(page.getByText("独立质量检查已完成")).toBeVisible()
  await page.getByRole("button", { name: "确认锁稿" }).click()
  await page.getByRole("button", { name: "生成模拟发布数据" }).click()
  await page.getByRole("button", { name: "生成复盘" }).click()
  await expect(page.getByText("本次内容复盘")).toBeVisible()
  await expect(page.getByText("模拟数据，不代表真实平台表现")).toBeVisible()
  await expect(page.getByRole("navigation")).toHaveCount(0)

  await page.evaluate(() => window.localStorage.removeItem("content-prototype-run"))
  await page.reload()
  await expect(page.getByLabel("称呼")).toHaveCount(0)
  await expect(page.getByText("今天，先确定真正值得拍的一条")).toBeVisible()
  await expect(page.getByRole("button", { name: "当前 IP 示例团长" })).toBeVisible()
})
