import type { RunCommand, RunState } from "./models"

const transitions: Partial<Record<RunState, Partial<Record<RunCommand, RunState>>>> = {
  READY_FOR_TOPICS: { GENERATE_TOPICS: "GENERATING_TOPICS" },
  GENERATING_TOPICS: { TOPICS_GENERATED: "WAITING_TOPIC_SELECTION" },
  WAITING_TOPIC_SELECTION: { SELECT_TOPIC: "READY_FOR_SCRIPTS" },
  READY_FOR_SCRIPTS: { GENERATE_SCRIPTS: "GENERATING_SCRIPTS" },
  GENERATING_SCRIPTS: { SCRIPTS_GENERATED: "WAITING_SCRIPT_SELECTION" },
  WAITING_SCRIPT_SELECTION: { SELECT_SCRIPT: "READY_FOR_QA" },
  READY_FOR_QA: { RUN_QA: "RUNNING_QA" },
  RUNNING_QA: { QA_COMPLETED: "WAITING_LOCK_CONFIRMATION" },
  WAITING_LOCK_CONFIRMATION: { LOCK: "LOCKED" },
  LOCKED: { SIMULATE_PUBLICATION: "SIMULATING_PUBLICATION" },
  SIMULATING_PUBLICATION: { PUBLICATION_SIMULATED: "WAITING_REVIEW" },
  WAITING_REVIEW: { GENERATE_REVIEW: "REVIEWING" },
  REVIEWING: { REVIEW_COMPLETED: "REVIEWED" },
}

export function transition(current: RunState, command: RunCommand): RunState {
  const next = transitions[current]?.[command]
  if (!next) throw new Error(`INVALID_TRANSITION:${current}:${command}`)
  return next
}
